const keymap = {
    KeyQ: 'C5',
    Digit2: 'Cs5',
    KeyW: 'D5',
    Digit3: 'Ds5',
    KeyE: 'E5',
    KeyR: 'F5',
    Digit5: 'Fs5',
    KeyT: 'G5',
    Digit6: 'Gs5',
    KeyY: 'A5',
    Digit7: 'As5',
    KeyU: 'B5',
    KeyI: 'C6',
    Digit9: 'Cs6',
    KeyO: 'D6',
    Digit0: 'Ds6',
    KeyP: 'E6',

    KeyZ: 'C4',
    KeyS: 'Cs4',
    KeyX: 'D4',
    KeyD: 'Ds4',
    KeyC: 'E4',
    KeyV: 'F4',
    KeyG: 'Fs4',
    KeyB: 'G4',
    KeyH: 'Gs4',
    KeyN: 'A4',
    KeyJ: 'As4',
    KeyM: 'B4',
    Comma: 'C5',
    KeyL: 'Cs5',
    Period: 'D5',
    Semicolon: 'Ds5',
    Slash: 'E5',

    Backspace: 'none'
};

export default keymap;
